### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by WallZFE** [wzj5133329/retinaface_caffe#1]
您好。我按照你的要求修改了Makefile文件，把我的caffe路径添加进去了，在make时出现了错误：
`g++  -o retinaface  detect.o anchor_generator.o config.o tools.o main.o -lboost_system -lcaffe -lglog  -lprotobuf -lcudart  -lgflags   `pkg-config opencv 
/usr/bin/ld: cannot find -lcaffe
/usr/bin/ld: cannot find -lcudart
collect2: error: ld returned 1 exit status
Makefile:21: recipe for target 'retinaface' failed
make: *** [retinaface] Error 1`
请问您是怎么解决的，谢谢你了。

**Comment by wzj5133329** [comment]
你可以将你的caffe路径添加到环境变量里面试试
操作如下
1.sudo gedit /etc/bash.bashrc
添加类似如下
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/home/asd/Project/MobileNet-YOLO-master2/include
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/asd/Project/MobileNet-YOLO-master2/build/lib
export LIBRARY_PATH=$LIBRARY_PATH:/home/asd/Project/MobileNet-YOLO-master2/build/lib
2.source  /etc/bash.bashrc
3.sudo ldconfig
另外如果你没有cuda需要将-lcudart去掉

**Comment by wzj5133329** [comment]
> 您好。我按照你的要求修改了Makefile文件，把我的caffe路径添加进去了，在make时出现了错误：
> `g++ -o retinaface detect.o anchor_generator.o config.o tools.o main.o -lboost_system -lcaffe -lglog -lprotobuf -lcudart -lgflags `pkg-config opencv
> /usr/bin/ld: cannot find -lcaffe
> /usr/bin/ld: cannot find -lcudart
> collect2: error: ld returned 1 exit status
> Makefile:21: recipe for target 'retinaface' failed
> make: *** [retinaface] Error 1`
> 请问您是怎么解决的，谢谢你了。

你可以将你的caffe路径添加到环境变量里面试试
操作如下
1.sudo gedit /etc/bash.bashrc
添加类似如下
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/home/asd/Project/MobileNet-YOLO-master2/include
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/asd/Project/MobileNet-YOLO-master2/build/lib
export LIBRARY_PATH=$LIBRARY_PATH:/home/asd/Project/MobileNet-YOLO-master2/build/lib
2.source /etc/bash.bashrc
3.sudo ldconfig
另外如果你没有cuda需要将-lcudart去掉

**Comment by WallZFE** [comment]
嗯嗯，上面错误是因为相应的lib库路径没有找到导致的，我把lib库按照你的方法添加到bash.bashrc里后，make就成功了。谢谢你了
