### ISSUE TITLE
error C2065: “anchor”: 未声明的标识符 

### ISSUE THREAD

**Issue by youthM** [wzj5133329/retinaface_caffe#2]
在caffe-cpu下运行程序，在
void AnchorGenerator::landmark_pred(const CRect2f anchor, const std::vectorcv::Point2f& delta, std::vectorcv::Point2f& pts) {
float w = anchor[2] - anchor[0] + 1;
float h = anchor[3] - anchor[1] + 1;
float x_ctr = anchor[0] + 0.5 * (w - 1);
float y_ctr = anchor[1] + 0.5 * (h - 1);
pts.resize(delta.size());
for (int i = 0; i < delta.size(); ++i) {
pts[i].x = (delta[i].x*w + x_ctr)ratiow;
pts[i].y = (delta[i].yh + y_ctr)*ratioh;
}
}中出现以下问题， 请问是什么原因？ @wzj5133329 
![image](https://user-images.githubusercontent.com/37856024/62506955-2bda1200-b835-11e9-853c-4e5f9c5a330b.png)

**Comment by wzj5133329** [comment]
> 在caffe-cpu下运行程序，在
> void AnchorGenerator::landmark_pred(const CRect2f anchor, const std::vectorcv::Point2f& delta, std::vectorcv::Point2f& pts) {
> float w = anchor[2] - anchor[0] + 1;
> float h = anchor[3] - anchor[1] + 1;
> float x_ctr = anchor[0] + 0.5 * (w - 1);
> float y_ctr = anchor[1] + 0.5 * (h - 1);
> pts.resize(delta.size());
> for (int i = 0; i < delta.size(); ++i) {
> pts[i].x = (delta[i].x*w + x_ctr)ratiow;
> pts[i].y = (delta[i].yh + y_ctr)*ratioh;
> }
> }中出现以下问题， 请问是什么原因？ @wzj5133329
> ![image](https://user-images.githubusercontent.com/37856024/62506955-2bda1200-b835-11e9-853c-4e5f9c5a330b.png)



> 在caffe-cpu下运行程序，在
> void AnchorGenerator::landmark_pred(const CRect2f anchor, const std::vectorcv::Point2f& delta, std::vectorcv::Point2f& pts) {
> float w = anchor[2] - anchor[0] + 1;
> float h = anchor[3] - anchor[1] + 1;
> float x_ctr = anchor[0] + 0.5 * (w - 1);
> float y_ctr = anchor[1] + 0.5 * (h - 1);
> pts.resize(delta.size());
> for (int i = 0; i < delta.size(); ++i) {
> pts[i].x = (delta[i].x*w + x_ctr)ratiow;
> pts[i].y = (delta[i].yh + y_ctr)*ratioh;
> }
> }中出现以下问题， 请问是什么原因？ @wzj5133329
> ![image](https://user-images.githubusercontent.com/37856024/62506955-2bda1200-b835-11e9-853c-4e5f9c5a330b.png)

你是在windows上编译的吗？目前还没将工程在win上实现，请先确认caffe的环境在vs上已经配置好
