### ISSUE TITLE
４G显存还不够？？？

### ISSUE THREAD

**Issue by mhsszm** [wzj5133329/retinaface_caffe#3]
I0809 11:51:02.075692  7224 upgrade_proto.cpp:80] Successfully upgraded batch norm layers using deprecated params.
channels3
img10480
F0809 11:51:02.320047  7224 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
看了一下显存是满了，改哪里可以使降显存吗？

**Comment by wzj5133329** [comment]
你可以将你的prototxt网络的输入设置小一点,这里给的是1920*1080，所以需要显存会比较多
